import { PageLayout, Section, InfoRow } from './PageLayout';

export const PrivacyPolicyPage = () => {
    return (
        <PageLayout title="Privacy Policy" lastUpdated="February 20, 2026">
            <p className="text-sm leading-relaxed" style={{ color: 'var(--muted)' }}>
                This Privacy Policy describes how <strong style={{ color: 'var(--text)' }}>VELORIA TECH (OPC) PRIVATE LIMITED</strong> ("Company", "we", "us", or "our") collects, uses, and shares your information when you use the Aicrix platform ("Application") and the website at <a href="https://aicrix.com" >https://aicrix.com</a> ("Website"). By using our Service, you agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <Section title="1. Interpretation and Definitions">
                <p>The following definitions apply throughout this Privacy Policy:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li><strong className="text-white/50">Account</strong> means a unique account created for you to access our Service or parts of our Service.</li>
                    <li><strong className="text-white/50">Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for election of directors or other managing authority.</li>
                    <li><strong className="text-white/50">Application</strong> refers to Aicrix, the AI-powered cricket advisory platform provided by the Company.</li>
                    <li><strong className="text-white/50">Company</strong> refers to VELORIA TECH (OPC) PRIVATE LIMITED, 12-132, Main Road, Pedda Devaram Padu, Ammanabrolu, Ongole Mandal, Prakasham, 523180, Andhra Pradesh, India.</li>
                    <li><strong className="text-white/50">Cookies</strong> are small files placed on your device (computer, mobile, or tablet) by a website, containing details of your browsing history and other usage information.</li>
                    <li><strong className="text-white/50">Country</strong> refers to Andhra Pradesh, India.</li>
                    <li><strong className="text-white/50">Device</strong> means any device that can access the Service, such as a computer, cellphone, or digital tablet.</li>
                    <li><strong className="text-white/50">Personal Data</strong> means any information that relates to an identified or identifiable individual.</li>
                    <li><strong className="text-white/50">Service</strong> refers to the Application and the Website, individually or collectively.</li>
                    <li><strong className="text-white/50">Third-party Social Media Service</strong> refers to any website or social network through which a User can log in or create an account to use the Service.</li>
                    <li><strong className="text-white/50">Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., page visit duration).</li>
                    <li><strong className="text-white/50">Website</strong> refers to Aicrix, accessible from <a href="https://aicrix.com" >https://aicrix.com</a>.</li>
                    <li><strong className="text-white/50">You</strong> means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
                </ul>
            </Section>

            <Section title="2. Types of Data Collected">
                <h3 className="text-white/60 font-medium text-sm mt-4 mb-2">2.1 Personal Data</h3>
                <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Phone number</li>
                    <li>Profile photo (optional)</li>
                    <li>Usage Data</li>
                </ul>

                <h3 className="text-white/60 font-medium text-sm mt-4 mb-2">2.2 Usage Data</h3>
                <p>Usage Data is collected automatically when using the Service. It may include information such as:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li>Your Device's Internet Protocol address (IP address)</li>
                    <li>Browser type and browser version</li>
                    <li>The pages of our Service that you visit, the time and date of your visit, the time spent on those pages</li>
                    <li>Unique device identifiers and other diagnostic data</li>
                    <li>When accessing the Service via a mobile device: the type of mobile device, unique ID, IP address, mobile operating system, mobile Internet browser type, and other diagnostic data</li>
                    <li>Information your browser sends whenever you visit our Service or access it through a mobile device</li>
                </ul>

                <h3 className="text-white/60 font-medium text-sm mt-4 mb-2">2.3 Information from Third-Party Social Media Services</h3>
                <p>The Company allows you to create an account and log in to use the Service through the following Third-party Social Media Services:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li>Google</li>
                    <li>Facebook</li>
                    <li>Twitter (X)</li>
                    <li>LinkedIn</li>
                    <li>Apple</li>
                </ul>
                <p className="mt-2">If you decide to register through or otherwise grant us access to a Third-Party Social Media Service, we may collect Personal Data that is already associated with your Third-Party Social Media Service's account, such as your name, your email address, your activities, or your contact list associated with that account. You may also have the option of sharing additional information with the Company through your Third-Party Social Media Service's account.</p>

                <h3 className="text-white/60 font-medium text-sm mt-4 mb-2">2.4 Information Collected While Using the Application</h3>
                <p>While using our Application, in order to provide features of our Application, we may collect, with your prior permission:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li><strong className="text-white/50">Camera and photo library:</strong> For profile photos (optional)</li>
                    <li><strong className="text-white/50">Push notifications:</strong> To deliver match alerts, prediction updates, and important announcements</li>
                </ul>
                <p className="mt-2">We use this information to provide features of our Service, to improve and customize our Service. The information may be uploaded to the Company's servers or it may simply be stored on your device. You can enable or disable access to this information at any time, through your Device settings.</p>

                <h3 className="text-white/60 font-medium text-sm mt-4 mb-2">2.5 Analytics and Crash Reporting</h3>
                <p>We use the following third-party analytics and crash reporting services to help us understand how you use the Application and to improve its performance and stability:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li><strong className="text-white/50">Firebase Analytics (Google):</strong> Collects usage data including app opens, screen views, user engagement events, in-app purchase events, device type, operating system, and country/region. This data is used to understand user behavior, improve features, and optimize the user experience. Firebase Analytics may use device advertising identifiers (IDFA on iOS, Advertising ID on Android) for attribution purposes.</li>
                    <li><strong className="text-white/50">Firebase Crashlytics (Google):</strong> Automatically collects crash reports and diagnostic data including device type, operating system version, stack traces, and the state of the Application at the time of a crash. This data is used to identify, diagnose, and fix stability issues to improve Application reliability.</li>
                </ul>
                <p className="mt-2">These services are provided by Google LLC. Data collected by Firebase is processed in accordance with <a href="https://policies.google.com/privacy"  target="_blank" rel="noopener noreferrer">Google's Privacy Policy</a> and <a href="https://firebase.google.com/support/privacy"  target="_blank" rel="noopener noreferrer">Firebase's data processing terms</a>. You may opt out of analytics data collection through the Application settings where available, or by adjusting your device's advertising and tracking preferences.</p>

                <h3 className="text-white/60 font-medium text-sm mt-4 mb-2">2.6 Advertising</h3>
                <p>The Application displays advertisements provided by third-party advertising networks. We use the following advertising services:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li><strong className="text-white/50">Google AdMob:</strong> Serves advertisements within the Application, including banner ads, interstitial ads, and rewarded ads. AdMob may collect and use data including your device's advertising identifier (IDFA on iOS, Advertising ID on Android), IP address, device information, and general usage data to deliver relevant advertisements.</li>
                </ul>
                <p className="mt-2">Advertising networks may use cookies, mobile advertising identifiers, and similar technologies to collect information about your activity within the Application and across other apps and websites to provide you with targeted (personalized) advertisements. The types of data that may be collected by advertising partners include:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li>Device type, model, and operating system</li>
                    <li>Advertising identifiers (IDFA / Advertising ID)</li>
                    <li>IP address and approximate location (country/region level)</li>
                    <li>App usage and interaction data</li>
                    <li>Ad interaction data (views, clicks)</li>
                </ul>
                <p className="mt-2"><strong className="text-white/50">Opting Out of Personalized Ads:</strong> You can opt out of personalized advertising by adjusting your device settings:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li><strong className="text-white/50">iOS:</strong> Settings → Privacy & Security → Tracking → disable "Allow Apps to Request to Track"</li>
                    <li><strong className="text-white/50">Android:</strong> Settings → Privacy → Ads → select "Delete advertising ID" or "Opt out of Ads Personalization"</li>
                </ul>
                <p className="mt-2">Even if you opt out of personalized ads, you will still see non-personalized advertisements within the Application. For more information about Google's advertising practices, visit <a href="https://policies.google.com/technologies/ads"  target="_blank" rel="noopener noreferrer">Google's Advertising Policies</a>.</p>
            </Section>

            <Section title="3. Tracking Technologies and Cookies">
                <p>We use Cookies and similar tracking technologies to track the activity on our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service. The technologies we use may include:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li><strong className="text-white/50">Cookies or Browser Cookies:</strong> A cookie is a small file placed on your Device. You can instruct your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you may not be able to use some parts of our Service. Unless you have adjusted your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
                    <li><strong className="text-white/50">Web Beacons:</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company to count users who have visited those pages or opened an email and for other related website statistics.</li>
                </ul>
                <p className="mt-2">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when you go offline, while Session Cookies are deleted as soon as you close your web browser.</p>
                <p className="mt-2">We use both Session and Persistent Cookies for the purposes set out below:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li><strong className="text-white/50">Necessary / Essential Cookies</strong> — Type: Session Cookies. Purpose: To provide you with services available through the Website and enable you to use some of its features. They help authenticate users and prevent fraudulent use of user accounts.</li>
                    <li><strong className="text-white/50">Cookies Policy / Notice Acceptance Cookies</strong> — Type: Persistent Cookies. Purpose: To identify if users have accepted the use of cookies on the Website.</li>
                    <li><strong className="text-white/50">Functionality Cookies</strong> — Type: Persistent Cookies. Purpose: To remember choices you make when you use the Website (such as your login details or language preference).</li>
                </ul>
            </Section>

            <Section title="4. Use of Your Personal Data">
                <p>The Company may use Personal Data for the following purposes:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li><strong className="text-white/50">To provide and maintain our Service,</strong> including to monitor the usage of our Service.</li>
                    <li><strong className="text-white/50">To manage your Account:</strong> to manage your registration as a user of the Service. The Personal Data you provide can give you access to different functionalities of the Service that are available to you as a registered user.</li>
                    <li><strong className="text-white/50">For the performance of a contract:</strong> the development, compliance, and undertaking of the purchase contract for the products, items, or services you have purchased or of any other contract with us through the Service.</li>
                    <li><strong className="text-white/50">To contact you:</strong> by email, telephone calls, SMS, push notifications, or other equivalent forms of electronic communication regarding updates or informative communications related to the functionalities, products, or contracted services, including security updates.</li>
                    <li><strong className="text-white/50">To provide you</strong> with news, special offers, and general information about other goods, services, and events which we offer that are similar to those you have already purchased or enquired about, unless you have opted not to receive such information.</li>
                    <li><strong className="text-white/50">To manage your requests:</strong> to attend and manage your requests to us.</li>
                    <li><strong className="text-white/50">For business transfers:</strong> to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding.</li>
                    <li><strong className="text-white/50">For other purposes:</strong> data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns, and evaluating and improving our Service, products, services, marketing, and your experience.</li>
                </ul>
            </Section>

            <Section title="5. Sharing of Your Personal Data">
                <p>We may share your personal information in the following situations:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li><strong className="text-white/50">With Analytics Providers:</strong> We share anonymized and aggregated usage data with Firebase Analytics and Firebase Crashlytics (Google LLC) to analyze app usage patterns, monitor performance, and diagnose technical issues.</li>
                    <li><strong className="text-white/50">With Advertising Partners:</strong> We share device identifiers, ad interaction data, and general usage information with advertising networks (such as Google AdMob) to serve relevant advertisements within the Application. This data is used for ad delivery, measurement, and performance optimization.</li>
                    <li><strong className="text-white/50">With App Store Platforms:</strong> When you make In-App Purchases, your payment information is processed directly by Apple (App Store) or Google (Play Store). We do not collect or store your payment or billing details.</li>
                    <li><strong className="text-white/50">For Business Transfers:</strong> in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</li>
                    <li><strong className="text-white/50">With Affiliates:</strong> including our parent company, VELORIA TECH (OPC) PRIVATE LIMITED, and any subsidiaries, joint venture partners, or other companies that we control or that are under common control with us.</li>
                    <li><strong className="text-white/50">With Other Users:</strong> when you share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
                    <li><strong className="text-white/50">With your consent:</strong> we may disclose your personal information for any other purpose with your consent.</li>
                </ul>
                <p className="mt-2">All data collected through the Platform — personal and analytics data — is shared with and maintained by the parent company, VELORIA TECH (OPC) PRIVATE LIMITED. We do not sell your Personal Data to third parties.</p>
            </Section>

            <Section title="6. Retention of Your Personal Data">
                <p>The Company will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                <p className="mt-2">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>
            </Section>

            <Section title="7. Transfer of Your Personal Data">
                <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
                <p className="mt-2">Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
                <p className="mt-2">The Company will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
            </Section>

            <Section title="8. Disclosure of Your Personal Data">
                <h3 className="text-white/60 font-medium text-sm mt-3 mb-2">8.1 Business Transactions</h3>
                <p>If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

                <h3 className="text-white/60 font-medium text-sm mt-3 mb-2">8.2 Law Enforcement</h3>
                <p>Under certain circumstances, the Company may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).</p>

                <h3 className="text-white/60 font-medium text-sm mt-3 mb-2">8.3 Other Legal Requirements</h3>
                <p>The Company may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li>Comply with a legal obligation</li>
                    <li>Protect and defend the rights or property of the Company</li>
                    <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>Protect the personal safety of Users of the Service or the public</li>
                    <li>Protect against legal liability</li>
                </ul>
            </Section>

            <Section title="9. Delete Your Personal Data">
                <p>You have the right to delete or request that we assist in deleting the Personal Data that we have collected about you.</p>
                <p className="mt-2">Our Service may give you the ability to delete certain information about you from within the Service. You may update, amend, or delete your information at any time by signing in to your Account, if you have one, and visiting the account settings section that allows you to manage your personal information. You may also contact us to request access to, correct, or delete any personal information that you have provided to us.</p>
                <p className="mt-2">Please note, however, that we may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
            </Section>

            <Section title="10. Security of Your Personal Data">
                <p>The security of your Personal Data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
                <p className="mt-2">We employ industry-standard security measures including:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li>Encrypted data transmission (SSL/TLS)</li>
                    <li>Secure data storage with access controls</li>
                    <li>Regular security audits and vulnerability assessments</li>
                    <li>Employee training on data protection best practices</li>
                    <li>Incident response procedures for data breaches</li>
                </ul>
            </Section>

            <Section title="11. Children's Privacy">
                <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from anyone under the age of 13 without verification of parental consent, we take steps to remove that information from our servers.</p>
                <p className="mt-2">If we need to rely on consent as a legal basis for processing your information and your country requires consent from a parent, we may require your parent's consent before we collect and use that information.</p>
            </Section>

            <Section title="12. Links to Other Websites">
                <p>Our Service may contain links to other websites that are not operated by us. If you click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
                <p className="mt-2">We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.</p>
            </Section>

            <Section title="13. Changes to This Privacy Policy">
                <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date at the top of this Privacy Policy.</p>
                <p className="mt-2">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                <p className="mt-2">Where required by applicable law, we will notify you via email and/or a prominent notice on our Service prior to the change becoming effective.</p>
            </Section>

            <Section title="14. Your Data Protection Rights">
                <p>Depending on your location and applicable data protection laws, you may have the following rights regarding your Personal Data:</p>
                <ul className="list-disc list-inside text-white/40 text-sm space-y-1.5 pl-1 mt-2">
                    <li><strong className="text-white/50">Right to Access:</strong> You have the right to request copies of your Personal Data.</li>
                    <li><strong className="text-white/50">Right to Rectification:</strong> You have the right to request that we correct any information you believe is inaccurate or complete information you believe is incomplete.</li>
                    <li><strong className="text-white/50">Right to Erasure:</strong> You have the right to request that we erase your Personal Data, under certain conditions.</li>
                    <li><strong className="text-white/50">Right to Restrict Processing:</strong> You have the right to request that we restrict the processing of your Personal Data, under certain conditions.</li>
                    <li><strong className="text-white/50">Right to Object to Processing:</strong> You have the right to object to our processing of your Personal Data, under certain conditions.</li>
                    <li><strong className="text-white/50">Right to Data Portability:</strong> You have the right to request that we transfer the data collected to another organization, or directly to you, under certain conditions.</li>
                </ul>
                <p className="mt-2">If you make a request, we have one month to respond to you. To exercise any of these rights, please contact us at our contact details below.</p>
            </Section>

            <Section title="15. Contact Us">
                <p>If you have any questions about this Privacy Policy, you can contact us:</p>
                <div className="p-4 rounded-xl page-card mt-2">
                    <InfoRow label="Company" value="VELORIA TECH (OPC) PRIVATE LIMITED" />
                    <InfoRow label="Email" value="support@aicrix.com" href="mailto:support@aicrix.com?subject=Privacy Inquiry" />
                    <InfoRow label="Phone" value="+91 95059 62262" href="tel:+919505962262" />
                    <InfoRow label="Website" value="https://aicrix.com/contact-us" href="/contact-us" />
                    <InfoRow label="Mailing Address" value="12-132, Main Road, Pedda Devaram Padu, Ammanabrolu, Ongole Mandal, Prakasham, 523180, Andhra Pradesh, India" />
                </div>
            </Section>
        </PageLayout>
    );
};
